tango_with_django_project/myrango/urls.py
from django.conf.urls import url
from myrango import views


app_name = 'myrango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^like/$', views.like_category, name='like_category'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
    # url(r'^logout/$', views.user_logout, name='logout'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.urls import path, reverse
from myrango import views
from django.conf import settings
from django.conf.urls.static import static

from registration.backends.simple.urls import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user=None):
        return reverse('myrango:register_profile')


urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^myrango/', include('myrango.urls')),
                  url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
                  url(r'^accounts/', include('registration.backends.simple.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/myrango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/myrango/forms.py
from django import forms
from .models import Page, Category, UserProfile
from django.contrib.auth.models import User


class CategoryFrom(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text='Please enter the title of the page')
    url = forms.URLField(max_length=128, help_text='Please enter the URL of the page')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category', )

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

tango_with_django_project/myrango/views.py
from datetime import datetime

from django.shortcuts import render
from .models import *
from .forms import CategoryFrom, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from .webhose_search import run_query
from django.shortcuts import redirect


# Create your views here.
def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list,
                    'pages': page_list}
    response = render(request, 'myrango/index.html', context_dict)
    visitor_cookie_handler(request, response)
    return response


def about(request):
    return render(request, 'myrango/about.html')


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    context_dict['query'] = category.name
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            result_list = run_query(query)
            context_dict['query'] = query
            context_dict['result_list'] = result_list

    return render(request, 'myrango/category.html', context_dict)


def add_category(request):
    form = CategoryFrom()

    if request.method == "POST":
        form = CategoryFrom(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'myrango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
            else:
                print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'myrango/add_page.html', context_dict)


def register(request):
    registered = True

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'myrango/register.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Your Myrango account is disabled')
        else:
            print('Invalid login details:{0}, {1}'.format(username, password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'myrango/login.html', {})


@login_required
def restricted(request):
    return HttpResponse('Since you`re logged in, you can see this text!')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponse('he;;0')


def visitor_cookie_handler(request, response):
    visits = int(request.COOKIES.get('visits', '1'))

    last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        response.set_cookie('last_visit', str(datetime.now()))
    else:
        response.set_cookie('last_visit', last_visit_cookie)
    response.set_cookie('visit', visits)


def search(request):
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
    return render(request, 'myrango/search.html', {'result_list': result_list, 'query': query})


def track_url(request):
    page_id = None
    url = '/myrango/'
    if request.method == "GET":
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.save()
                url = page.url
            except:
                pass

    return redirect(url)


@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect('myrango:index')
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'myrango/profile_registration.html', context_dict)


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('myrango:profile', user.username)
        else:
            print(form.errors)

    return render(request, 'myrango/profile.html', {'userprofile': userprofile, 'selecteduser': user, 'form': form})


@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=cat_id)
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()

    return HttpResponse(likes)


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)
    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list


def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)
    return render(request, 'myrango/cats.html', {'cats': cat_list})


@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()

    return render(request, 'myrango/list_profiles.html', {'userprofile_list': userprofile_list})

tango_with_django_project/templates/myrango/about.html
{% extends 'myrango/base.html' %}
{% load static %}
    <title>
        {% block title_block %}
        About
        {% endblock %}
    </title>
{% block body_block %}
<p>This tutorial has been put together by Lilin</p>
<div>

{#        <img src=" {{ MEDIA_URL }}1.jpg"#}
{#             alt="Picture of Myrango"/>#}
</div>
<img src="{% static "images/9.jpg" %}"
             alt="Picture of Myrango"/>
{% endblock %}

tango_with_django_project/templates/myrango/add_category.html
{% extends "myrango/base.html" %}
{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}
    <form id="category_form" method="post" action="/myrango/add_category/">
    <h2 class="form-signin-heading">Add a Category</h2>
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field}}
    {% endfor %}
<input class="btn btn-primary" type="submit"
       name="submit" value="Create Category">
    </form>
{% endblock %}

tango_with_django_project/templates/myrango/add_page.html
{% extends "myrango/base.html" %}
{% block title %}
    Add Page
{% endblock %}


{% block body_block %}
{% if category %}
<h1>Add a Page to {{ category.name }}</h1>
<form role="form" id="page_form" method="post"
      action="/myrango/category/{{ category.slug }}/add_page/">
<h2 class="form-signin-heading">Add a Page to
<a href="/myrango/category/{{ category.slug }}/">{{ category.name }}</a></h2>
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
{% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}
    {{ field }}
{% endfor %}
<br/>
<button class="btn btn-primary" type="submit" name="submit">Add Page</button>
</form>
{% else %}
    The specified category does not exist!
{% endif %}
{% endblock %}

tango_with_django_project/templates/myrango/base.html
{#<!DOCTYPE html>#}
{#{% load static %}#}
{#{% load myrango_template_tags %}#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>#}
{#        {% block title_block %}#}
{#            How to Tango with Django!#}
{#        {% endblock %}#}
{#    </title>#}
{#</head>#}
{#<body>#}
{#<div>#}
{#    {% block sidebar_block %}#}
{#        {% get_category_list category %}#}
{#    {% endblock %}#}
{#</div>#}
{##}
{#<div>#}
{#    {% block body_block %}#}
{#    {% endblock %}#}
{#</div>#}
{#<hr/>#}
{#<div>#}
{#    <ul>#}
{#        {% if user.is_authenticated %}#}
{#            <li><a href="{% url 'myrango:add_category' %}">Add New Category</a></li>#}
{#            <li><a href="{% url 'myrango:restricted' %}">Restricted Page</a></li>#}
{#            <li><a href="{% url 'auth_logout' %}?next=/myrango/">Logout</a></li>#}
{#        {% else %}#}
{#            <li><a href="{% url 'auth_login' %}">Login</a></li>#}
{#            <li><a href="{% url 'registration_register' %}">Register Here</a></li>#}
{#        {% endif %}#}
{#        <li><a href="{% url 'myrango:about' %}">About</a></li>#}
{#        <li><a href="{% url 'myrango:index' %}">Index</a></li>#}
{#    </ul>#}
{#</div>#}
{#</body>#}
{#</html>#}


<!DOCTYPE html>
{% load static %}
<script src="{% static 'js/jquery-3.5.1.js' %}"></script>
<script src="{% static 'js/jquery.cycle.all.js' %}"></script>
<script src="{% static 'js/myrango-ajax.js' %}"></script>
<script src="{% static 'js/cycle.js' %}"></script>
{#{% load myrango_template_tags %}#}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <meta name="description" charset="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/2.jpg' %}">

    <title>
        Myrango - {% block title %}How to Myrango with Django!{% endblock %}
    </title>
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href=
                  "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
          rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/script01.css' %}">
</head>
<body>

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
            aria-controls="navbar"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand" href="{% url 'myrango:index' %}">Myrango</a>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'myrango:index' %}">
                    Home
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'myrango:about' %}">
                    About
                </a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myrango:restricted' %}">
                        Restricted Page
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myrango:add_category' %}">
                        Add a New Category
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myrango:profile' user.username%}">
                        Profile
                    </a>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myrango:list_profiles' %}">
                        List Profiles
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_logout' %}?next=/myrango/">
                        Logout
                    </a>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration_register' %}">
                        Register Here
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_login' %}">
                        Login
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
{#            <input class="input-medium search-query" type="text"#}
{#            name="suggestion" value="" id="suggestion"/>#}

            <ul class="nav nav-list flex-column">
                <li class="nav-item">Type to find a category</li>
                <form>
                    <li class="nav-item"><input class="search-query form-control" type="text"
                    name="suggestion" value="" id="suggestion"/>
                    </li>
                </form>
            </ul>
            <hr>
            <div id="cats">
            </div>
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
            {% block body_block %}
            {% endblock %}
        </div>
    </div>
</div>

<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>

<script
        src=
                "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
</script>

</body>
</html>

tango_with_django_project/templates/myrango/base_bootstrap.html
<!DOCTYPE html>
{% load static %}
{% load myrango_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <meta name="description" charset="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/2.jpg' %}">

    <title>
        Myrango - {% block title %}How to Myrango with Django!{% endblock %}
    </title>
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href=
                  "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
          rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
            aria-controls="navbar"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand" href="{% url 'index' %}">Myrango</a>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">
                    Home
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">
                    About
                </a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restricted' %}">
                        Restricted Page
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_category' %}">
                        Add a New Category
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">
                        Logout
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration_register' %}">
                        Register Here
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_login' %}">
                        Login
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
            {% block body_block %}
            {% endblock %}
        </div>
    </div>
</div>

<script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>

<script
        src=
                "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
</script>

</body>
</html>

tango_with_django_project/templates/myrango/category.html
{% extends 'myrango/base.html' %}
{% load static %}

{% block title_block%}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        <div>
        <strong id="like_count">{{ category.likes }}</strong> People like this category
        <button id="likes" data-catid="{{ category.id }}"
                class="btn btn-primary btn-sm" type="button">Like</button>
        </div>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{% url 'myrango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a></li>
                    {% if page.views > 1 %}
                        ({{ page.views }} views)
                    {% elif page.views == 1 %}
                        ({{ page.views }} view)
                    {% endif %}
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        <br>
        {% if user.is_authenticated %}
        <a href="{% url 'myrango:add_page' category.slug %}">Add Page</a>
            {% endif %}
        <br>
    {% else %}
        The specified category does not exist!
    {% endif %}

    <form class="form-inline" id="user_form" method="post" action="{% url 'myrango:show_category' category.slug %}">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query"/>
            </div>
            <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
        </form>


    <div>
            {% if result_list %}
                <h3>Results</h3>
                <div class="list-group">
                    {% for result in result_list %}
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">
                                <a href="{{ result.link }}">{{ result.title }}</a>
                            </h4>
                            <p class="list-group-item-text">{{ result.summary }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

{% endblock %}

tango_with_django_project/templates/myrango/cats.html
<ul>
    {% if cats %}
        <p><b>Category</b></p>
        {% for c in cats %}
            {% if c == act_cat %}
            <li>
            <strong>
                <a href="{% url 'myrango:show_category' c.slug%}">{{ c.name }}</a>
                </strong>
            </li>
            {% else %}
            <li><a href="{% url 'myrango:show_category' c.slug%}">{{ c.name }}</a></li>
                        {% endif %}
        {% endfor %}
        {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

tango_with_django_project/templates/myrango/index.html
{% extends 'myrango/base.html' %}
{% load static %}
{% block title_block %}
    Index
{% endblock %}


{% block body_block %}
<div class="jumbotron">
<h1 class="display-3">Myrango says...</h1>
{% if user.is_authenticated %}
    <h1>hey there {{ user.username }}!</h1>
{% else %}
    hey there partner!
{% endif %}
</div>

<div class="row marketing">
<div class="col-lg-6">
<h4>Most Liked Categories</h4>
<p>
    {% if categories %}
        <ul class="list-group">
            {% for catetory in categories %}
                <li class="list-group-item">
                    <a href="/myrango/category/{{ catetory.slug }}">{{ catetory.name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <strong>There are no categories present.</strong>
    {% endif %}
</p>
</div>
<div class="col-lg-6">
<h4>Most Viewed Pages</h4>
<p>
    {% if pages %}
        <ul class="list-group">
            {% for page in pages %}
                <li class="list-group-item">
                    <a href="{{ page.url }}">{{ page.title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <strong>There are no pages present.</strong>
    {% endif %}
</p>
</div>
    </div>
    <ul id="image">
    <li>
        <img src="{% static 'images/1.jpg' %}" alt="Picture of Myrango" class="img_cycle" />
    </li>
    <li>
        <img src="{% static 'images/2.jpg' %}" alt="Picture of Myrango" class="img_cycle"/>
    </li>
    <li>
        <img src="{% static 'images/3.jpg' %}" alt="Picture of Myrango" class="img_cycle"/>
    </li>
    <li>
        <img src="{% static 'images/5.jpg' %}" alt="Picture of Myrango" class="img_cycle"/>
    </li>
    <li>
        <img src="{% static 'images/6.jpg' %}" alt="Picture of Myrango" class="img_cycle"/>
    </li>
    <li>
        <img src="{% static 'images/7.jpg' %}" alt="Picture of Myrango" class="img_cycle"/>
    </li>
    <li>
        <img src="{% static 'images/9.jpg' %}" alt="Picture of Myrango" class="img_cycle"/>
    </li>
    </ul>
{% endblock %}

tango_with_django_project/templates/myrango/profile_registration.html
{% extends 'myrango/base.html' %}
{% block title_block %}
    Registration - Step 2
{% endblock %}

{% block body_block %}
    <h1>Registration - Step 2</h1>
    <form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
{% endblock %}

tango_with_django_project/templates/myrango/search.html
{% extends 'myrango/base.html' %}
{% load static %}

{% block title %}
    Search
{% endblock %}

{% block body_block %}
    <div>
        <h1>Search with Myrango</h1>
        <br/>
        <form class="form-inline" id="user_form" method="post" action="{% url 'myrango:search' %}">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query"/>
            </div>
            <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
        </form>

        <div>
            {% if result_list %}
                <h3>Results</h3>
                <div class="list-group">
                    {% for result in result_list %}
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">
                                <a href="{{ result.link }}">{{ result.title }}</a>
                            </h4>
                            <p class="list-group-item-text">{{ result.summary }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}